# Generated by Django 3.2.5 on 2021-08-28 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=30)),
                ('ClassroomId', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='classroomid',
            new_name='ClassroomId',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='namelist',
        ),
        migrations.AddField(
            model_name='teacher',
            name='NameList',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
