# Generated by Django 3.2.5 on 2021-08-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0003_auto_20210828_0819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
