# Generated by Django 3.2.5 on 2021-08-31 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0005_studentattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
