# Generated by Django 3.2.5 on 2021-08-31 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0006_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAttendance',
            new_name='StudentSignIn',
        ),
    ]
