# Generated by Django 3.2.5 on 2021-09-01 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0007_rename_studentattendance_studentsignin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsignin',
            name='account',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
