# Generated by Django 3.2.5 on 2021-09-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0008_studentsignin_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsignin',
            name='ClassroomId',
        ),
        migrations.RemoveField(
            model_name='studentsignin',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='studentsignin',
            name='account',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='ClassroomId',
        ),
    ]
