# Generated by Django 3.2.5 on 2021-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0010_auto_20210902_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignin',
            name='ClassroomId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentsignin',
            name='UserId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentsignin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ClassroomId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='NameList',
            field=models.CharField(max_length=10000),
        ),
    ]
