# Generated by Django 3.2.5 on 2021-09-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0012_studentsignin_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsignin',
            name='account',
        ),
    ]
