# Generated by Django 3.2.5 on 2021-09-02 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0013_remove_studentsignin_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsignin',
            name='account',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
