# Generated by Django 3.2.5 on 2021-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0014_studentsignin_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignin',
            name='account',
            field=models.TextField(blank=True),
        ),
    ]
