# Generated by Django 3.2.5 on 2021-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0015_alter_studentsignin_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignin',
            name='ClassroomId',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentsignin',
            name='UserId',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentsignin',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ClassroomId',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='NameList',
            field=models.TextField(blank=True),
        ),
    ]
