# Generated by Django 3.2.5 on 2021-09-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollcall', '0016_auto_20210902_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignin',
            name='ClassroomId',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentsignin',
            name='UserId',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ClassroomId',
            field=models.URLField(blank=True),
        ),
    ]
